#The nexessary stuff/decessary stuff

base_url = "https://aryangupta01.github.io"
title = "Aryan Gupta - Portfolio"
description = ""
generate_feeds = true
compile_sass = true
minify_html = true

build_search_index = true

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
toc = true
use_cdn = false
search_bar = true

#Full path after the base URL required. So if you were to place it in "static" it would be "/favicon.ico"
favicon = "/icons/favicon/favicon.ico"

#This header image is used for SEO. For example if you were to share an image via Messenger/Instagram/Twitter a preview picture is also presented
headerImage = ""

# The icon is display besides the menu text but is not necessary. It needs to be placed under "menu_icon" in the static "folder"
menu = [
    { name = "Projects", url = "/projects", weight = 1, icon = "projects.png" },
    { name = "Resume", url = "/CV.pdf", weight = 1, icon = "resume3.png" }
]
#The icons available can be found in "social_icons" in the "static" folder
socials = [
    { name = "email", url = "mailto:aryangupta210302@gmail.com", icon = "email" },
    { name = "github", url = "https://github.com/aryangupta01", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/aryan-gupta-5419ab203/", icon = "linkedin" },
]
